### ISSUE TITLE
Saved data is grouped

### ISSUE THREAD

**Issue by jbourak** [UBC-MDS/taxyvr#4]
https://github.com/UBC-MDS/taxyvr/blob/837526f4fb8cf77960381c92397860990edfb61f/data-raw/tax_2019.R#L29

(Appears in all `data-raw/tax_20XX.R` scripts)

Need to `ungroup()` here to avoid errors like `Adding missing grouping variables: 'folio'` when selecting

**Comment by hfboyce** [comment]
@jbourak do you mean just 
```
 ll_df <- combo %>% group_by(folio) %>% slice(1)  %>% ungroup()
``` 
I wasn't getting any errors but I can add it now!

**Comment by jbourak** [comment]
Yep! I was getting that error when trying to unselect the `folio` column since its used in the grouping

**Comment by hfboyce** [comment]
Ok closing issue fixed!
